// packages/svelte/src/listeners/FullscreenListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountFullscreenListener } from '@manapotion/core'

  import type { FullscreenChangePayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{ fullscreenChange: FullscreenChangePayload }>()

  onMount(() =>
    mountFullscreenListener({
      onFullscreenChange: payload => dispatch('fullscreenChange', payload),
    }),
  )
</script>

// packages/react/src/listeners/FullscreenListener.tsx
import { useEffect } from 'react'

import { FullscreenListenerProps, mountFullscreenListener } from '@manapotion/core'

export const FullscreenListener = ({ onFullscreenChange }: FullscreenListenerProps) => {
  useEffect(() => mountFullscreenListener({ onFullscreenChange }), [onFullscreenChange])

  return null
}
