// packages/svelte/src/listeners/KeyboardListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountKeyboardListener } from '@manapotion/core'

  import type { KeyDownPayload, KeyUpPayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{ keyDown: KeyDownPayload; keyUp: KeyUpPayload }>()

  onMount(() =>
    mountKeyboardListener({
      onKeyDown: payload => dispatch('keyDown', payload),
      onKeyUp: payload => dispatch('keyUp', payload),
    }),
  )
</script>

// packages/react/src/listeners/KeyboardListener.tsx
import { useEffect } from 'react'

import { KeyboardListenerProps, mountKeyboardListener } from '@manapotion/core'

export const KeyboardListener = ({ onKeyDown, onKeyUp }: KeyboardListenerProps) => {
  useEffect(() => mountKeyboardListener({ onKeyDown, onKeyUp }), [onKeyDown, onKeyUp])

  return null
}
