// packages/svelte/src/listeners/MouseButtonsListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import {
    LeftMouseDownPayload,
    LeftMouseUpPayload,
    MiddleMouseDownPayload,
    MiddleMouseUpPayload,
    mountMouseButtonsListener,
    RightMouseDownPayload,
    RightMouseUpPayload,
  } from '@manapotion/core'

  const dispatch = createEventDispatcher<{
    leftMouseDown: LeftMouseDownPayload
    leftMouseUp: LeftMouseUpPayload
    middleMouseDown: MiddleMouseDownPayload
    middleMouseUp: MiddleMouseUpPayload
    rightMouseDown: RightMouseDownPayload
    rightMouseUp: RightMouseUpPayload
  }>()

  onMount(() =>
    mountMouseButtonsListener({
      onLeftMouseDown: payload => dispatch('leftMouseDown', payload),
      onLeftMouseUp: payload => dispatch('leftMouseUp', payload),
      onMiddleMouseDown: payload => dispatch('middleMouseDown', payload),
      onMiddleMouseUp: payload => dispatch('middleMouseUp', payload),
      onRightMouseDown: payload => dispatch('rightMouseDown', payload),
      onRightMouseUp: payload => dispatch('rightMouseUp', payload),
    }),
  )
</script>

// packages/react/src/listeners/MouseButtonsListener.tsx
import { useEffect } from 'react'

import { mountMouseButtonsListener, MouseButtonsListenerProps } from '@manapotion/core'

export const MouseButtonsListener = ({
  onLeftMouseDown,
  onMiddleMouseDown,
  onRightMouseDown,
  onLeftMouseUp,
  onMiddleMouseUp,
  onRightMouseUp,
}: MouseButtonsListenerProps) => {
  useEffect(
    () =>
      mountMouseButtonsListener({
        onLeftMouseDown,
        onMiddleMouseDown,
        onRightMouseDown,
        onLeftMouseUp,
        onMiddleMouseUp,
        onRightMouseUp,
      }),
    [],
  )

  return null
}
