// packages/svelte/src/listeners/PageFocusListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountBlurListener, mountFocusListener } from '@manapotion/core'

  import type { PageFocusChangePayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{ pageFocusChange: PageFocusChangePayload }>()

  onMount(() => {
    let unsubBlur = mountBlurListener({
      onPageFocusChange: payload => dispatch('pageFocusChange', payload),
    })
    const unsubFocus = mountFocusListener({
      onPageFocusChange: payload => dispatch('pageFocusChange', payload),
    })

    return () => {
      unsubBlur()
      unsubFocus()
    }
  })
</script>

// packages/react/src/listeners/PageFocusListener.tsx
import { useEffect } from 'react'

import { mountBlurListener, mountFocusListener, PageFocusListenerProps } from '@manapotion/core'

export const PageFocusListener = ({
  onPageFocusChange,
  clearInputsOnBlur = true,
}: PageFocusListenerProps) => {
  useEffect(() => mountBlurListener({ onPageFocusChange, clearInputsOnBlur }), [clearInputsOnBlur])
  useEffect(() => mountFocusListener({ onPageFocusChange }), [])

  return null
}
