// packages/svelte/src/listeners/PageVisibilityListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountPageVisibilityListener } from '@manapotion/core'

  import type { PageVisibilityPayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{ pageVisibilityChange: PageVisibilityPayload }>()

  onMount(() =>
    mountPageVisibilityListener({
      onPageVisibilityChange: payload => dispatch('pageVisibilityChange', payload),
    }),
  )
</script>

// packages/react/src/listeners/PageVisibilityListener.tsx
import { useEffect } from 'react'

import { mountPageVisibilityListener, PageVisibilityListenerProps } from '@manapotion/core'

export const PageVisibilityListener = ({ onPageVisibilityChange }: PageVisibilityListenerProps) => {
  useEffect(() => mountPageVisibilityListener({ onPageVisibilityChange }), [])

  return null
}
