// packages/svelte/src/listeners/PointerLockListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountPointerLockListener } from '@manapotion/core'

  import type { PointerLockChangePayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{ pointerLockChange: PointerLockChangePayload }>()

  onMount(() =>
    mountPointerLockListener({
      onPointerLockChange: payload => dispatch('pointerLockChange', payload),
    }),
  )
</script>

// packages/react/src/listeners/PointerLockListener.tsx
import { useEffect } from 'react'

import { mountPointerLockListener, PointerLockListenerProps } from '@manapotion/core'

export const PointerLockListener = ({ onPointerLockChange }: PointerLockListenerProps) => {
  useEffect(() => mountPointerLockListener({ onPointerLockChange }), [])

  return null
}
