// packages/svelte/src/listeners/ScreenOrientationListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountScreenOrientationListener } from '@manapotion/core'

  import type { ScreenOrientationChangePayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{
    screenOrientationChange: ScreenOrientationChangePayload
  }>()

  onMount(() =>
    mountScreenOrientationListener({
      onScreenOrientationChange: payload => dispatch('screenOrientationChange', payload),
    }),
  )
</script>

// packages/react/src/listeners/ScreenOrientationListener.tsx
import { useEffect } from 'react'

import { mountScreenOrientationListener, ScreenOrientationListenerProps } from '@manapotion/core'

export const ScreenOrientationListener = ({
  onScreenOrientationChange,
}: ScreenOrientationListenerProps) => {
  useEffect(
    () => mountScreenOrientationListener({ onScreenOrientationChange }),
    [onScreenOrientationChange],
  )

  return null
}
