// examples/react/src/components/Label.tsx
const Label = ({ name, value }: { name: string; value: boolean }) => {
  console.log(`Label ${name} rendered`)

  return (
    <span
      className={`label ${value === true ? 'label--positive' : value === false ? 'label--negative' : 'label--unknown'}`}
    >
      {value === true ? 'Yes' : value === false ? 'No' : 'Unknown'}
    </span>
  )
}

export default Label

// examples/svelte/src/components/Label.svelte
<script lang="ts">
  export let name: string
  export let value: boolean

  console.log(`Label ${name} rendered`)

  $: labelClass =
    value === true ? 'label--positive' : value === false ? 'label--negative' : 'label--unknown'
  $: labelText = value === true ? 'Yes' : value === false ? 'No' : 'Unknown'
</script>

<span class="label {labelClass}">
  {labelText}
</span>
