// examples/svelte/src/components/Item.svelte
<script lang="ts">
  export let isReactive: boolean | undefined = true
  export let name: string | undefined
</script>

<div class="item">
  <span>{isReactive ? '⚡️' : '🗿'}</span>
  <span class="item--main">
    <span class="item--name">{name}</span>
    <span>
      <slot name="label" />
      <slot name="value" />
    </span>
  </span>
  <slot name="extra" />
</div>

// examples/vue/src/components/Item.vue
<script setup lang="ts">
const props = defineProps({
  isReactive: { type: Boolean, default: true },
  name: { type: String, required: true },
})
</script>

<template>
  <div class="item">
    <span>{{ props.isReactive ? '⚡️' : '🗿' }}</span>
    <span class="item--main">
      <span class="item--name">{{ props.name }}</span>
      <span>
        <slot name="label" />
        <slot name="value" />
      </span>
    </span>
    <slot name="extra" />
  </div>
</template>
