// examples/svelte/src/components/Label.svelte
<script lang="ts">
  export let name: string
  export let value: boolean

  console.log(`Label ${name} rendered`)

  $: labelClass =
    value === true ? 'label--positive' : value === false ? 'label--negative' : 'label--unknown'
  $: labelText = value === true ? 'Yes' : value === false ? 'No' : 'Unknown'
</script>

<span class="label {labelClass}">
  {labelText}
</span>

// examples/vue/src/components/Label.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{ name: string; value: boolean }>()

console.log(`Label ${props.name} rendered`)

const labelClass = computed(() =>
  props.value === true
    ? 'label--positive'
    : props.value === false
      ? 'label--negative'
      : 'label--unknown',
)
const labelText = computed(() =>
  props.value === true ? 'Yes' : props.value === false ? 'No' : 'Unknown',
)
</script>

<template>
  <span :class="`label ${labelClass}`">
    {{ labelText }}
  </span>
</template>
