// packages/react/src/listeners/DeviceTypeListener.tsx
import { useEffect } from 'react'

import { mountDeviceTypeListener } from '@manapotion/core'

export type DeviceTypeListenerProps = {
  onUpdate?: ({ isDesktop, isMobile }: { isDesktop: boolean; isMobile: boolean }) => void
}

export const DeviceTypeListener = ({ onUpdate }: DeviceTypeListenerProps) => {
  useEffect(() => mountDeviceTypeListener({ onUpdate }), [onUpdate])

  return null
}

// packages/svelte/src/listeners/DeviceTypeListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountDeviceTypeListener } from '@manapotion/core'

  const dispatch = createEventDispatcher()

  onMount(() =>
    mountDeviceTypeListener({
      onDeviceTypeChange: ({ isDesktop, isMobile }) =>
        dispatch('deviceTypeChange', { isDesktop, isMobile }),
    }),
  )
</script>
