// packages/react/src/listeners/MouseScrollListener.tsx
import { useEffect } from 'react'

import { mountMouseScrollListener, MouseScrollListenerProps } from '@manapotion/core'

export const MouseScrollListener = ({
  onScroll,
  mouseScrollResetDelay = 100,
}: MouseScrollListenerProps) => {
  useEffect(
    () => mountMouseScrollListener({ onScroll, mouseScrollResetDelay }),
    [mouseScrollResetDelay],
  )

  return null
}

// packages/svelte/src/listeners/MouseScrollListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountMouseScrollListener } from '@manapotion/core'

  import type { MouseScrollPayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{ scroll: MouseScrollPayload }>()

  export let mouseScrollResetDelay: number | undefined = undefined

  onMount(() =>
    mountMouseScrollListener({
      onScroll: payload => dispatch('scroll', payload),
      // TODO: dynamically set this value
      mouseScrollResetDelay,
    }),
  )
</script>
