// packages/react/src/listeners/MouseMoveListener.tsx
import { useEffect } from 'react'

import { mountMouseMoveListener, MouseMoveListenerProps } from '@manapotion/core'

export const MouseMoveListener = ({
  mouseMovementResetDelay = 30,
  onMouseMove,
}: MouseMoveListenerProps) => {
  useEffect(
    () => mountMouseMoveListener({ onMouseMove, mouseMovementResetDelay }),
    [mouseMovementResetDelay],
  )

  return null
}

// packages/svelte/src/listeners/MouseMoveListener.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'

  import { mountMouseMoveListener, MouseMovePayload } from '@manapotion/core'

  const dispatch = createEventDispatcher<{ mouseMove: MouseMovePayload }>()

  export const mouseMovementResetDelay = 30

  onMount(() =>
    mountMouseMoveListener({
      onMouseMove: payload => dispatch('mouseMove', payload),
      // TODO: dynamically set this value
      mouseMovementResetDelay,
    }),
  )
</script>
