// examples/vue/src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

import {
  isDesktop,
  isLandscape,
  isLeftMouseDown,
  isMiddleMouseDown,
  isMobile,
  isPageFocused,
  isPageVisible,
  isPortrait,
  isRightMouseDown,
  keys,
  Listeners,
  mp,
  useAnimationFrame,
} from '@manapotion/vue'

import FullscreenButton from './FullscreenButton.vue'
import PointerLockButton from './PointerLockButton.vue'

const handleFullscreenChange = (event: Event) => {
  console.log('Fullscreen change!', event)
}

const handlePointerLockChange = (isPointerLocked: boolean) => {
  console.log('Pointer lock change!', isPointerLocked)
}

const mouseXRef = ref<HTMLSpanElement | null>(null)
const mouseYRef = ref<HTMLSpanElement | null>(null)
const mouseMovementXRef = ref<HTMLSpanElement | null>(null)
const mouseMovementYRef = ref<HTMLSpanElement | null>(null)
const windowWidthRef = ref<HTMLSpanElement | null>(null)
const windowHeightRef = ref<HTMLSpanElement | null>(null)

useAnimationFrame(() => {
  const { mouseX, mouseY, mouseMovementX, mouseMovementY, windowWidth, windowHeight } = mp()

  mouseXRef.value!.textContent = String(mouseX)
  mouseYRef.value!.textContent = String(mouseY)
  mouseMovementXRef.value!.textContent = String(mouseMovementX)
  mouseMovementYRef.value!.textContent = String(mouseMovementY)
  windowWidthRef.value!.textContent = String(windowWidth)
  windowHeightRef.value!.textContent = String(windowHeight)
})

const handlePageVisibilityChange = (isVisible: boolean) => {
  console.log('Page visibility change!', isVisible)
}

const jsonKeys = computed(() => JSON.stringify(keys.value))
</script>

<template>
  <FullscreenButton />
  <PointerLockButton />
  <div>Mouse position: <span ref="mouseXRef"></span> <span ref="mouseYRef"></span></div>
  <div>
    Mouse movement: <span ref="mouseMovementXRef"></span> <span ref="mouseMovementYRef"></span>
  </div>
  <div>Is page visible: {{ isPageVisible }}</div>
  <div>Is page focused: {{ isPageFocused }}</div>
  <div>Is mobile: {{ isMobile }}</div>
  <div>Is desktop: {{ isDesktop }}</div>
  <div>Is portrait: {{ isPortrait }}</div>
  <div>Is landscape: {{ isLandscape }}</div>
  <div>Window size: <span ref="windowWidthRef"></span> <span ref="windowHeightRef"></span></div>
  <div>
    Mouse buttons: Left: {{ isLeftMouseDown }}, Middle: {{ isMiddleMouseDown }}, Right:
    {{ isRightMouseDown }}
  </div>
  <div>
    <div>
      <b>Keyboard</b>
    </div>
    <textarea readonly class="h-[100px] w-full max-w-[500px]" :value="jsonKeys" />
  </div>

  <Listeners
    @fullscreenchange="handleFullscreenChange"
    @pointerlockchange="handlePointerLockChange"
    @visibilitychange="handlePageVisibilityChange"
  />
</template>

// example/src/App.tsx
import { useCallback, useRef, useState } from 'react'

import { MeshProps, useFrame } from '@react-three/fiber'
import {
  Canvas,
  enterFullscreen,
  exitFullscreen,
  Listeners,
  lockKeys,
  lockOrientation,
  lockPointer,
  mp,
  unlockKeys,
  unlockOrientation,
  useMP,
  useUIFrame,
} from 'manapotion'
import { Mesh } from 'three'

function Box(props: MeshProps) {
  const meshRef = useRef<Mesh>(null)
  const [hovered, setHover] = useState(false)
  const [active, setActive] = useState(false)

  useFrame((_, delta) => (meshRef.current!.rotation.x += delta))

  return (
    <mesh
      {...props}
      ref={meshRef}
      scale={active ? 1.5 : 1}
      onClick={() => setActive(!active)}
      onPointerOver={() => setHover(true)}
      onPointerOut={() => setHover(false)}
    >
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} />
    </mesh>
  )
}

const App = () => {
  const [renderer, setRenderer] = useState('WebGPU')
  const toggleRenderer = () => setRenderer(renderer === 'WebGPU' ? 'WebGL' : 'WebGPU')
  const isFullscreen = useMP(s => s.isFullscreen)
  const isPageVisible = useMP(s => s.isPageVisible)
  const isPointerLocked = useMP(s => s.isPointerLocked)
  const width = useMP(s => s.width)
  const height = useMP(s => s.height)
  const canHover = useMP(s => s.canHover)
  const mouseX = useMP(s => s.mouseX)
  const mouseY = useMP(s => s.mouseY)
  const mouseMovementX = useMP(s => s.mouseMovementX)
  const mouseMovementY = useMP(s => s.mouseMovementY)
  const isLeftMouseDown = useMP(s => s.isLeftMouseDown)
  const isMiddleMouseDown = useMP(s => s.isMiddleMouseDown)
  const isRightMouseDown = useMP(s => s.isRightMouseDown)
  const keys = useMP(s => s.keys)

  const liveMouseXRef = useRef<HTMLSpanElement>(null)
  const liveMouseYRef = useRef<HTMLSpanElement>(null)
  const liveMouseMovementXRef = useRef<HTMLSpanElement>(null)
  const liveMouseMovementYRef = useRef<HTMLSpanElement>(null)

  const liveWidthRef = useRef<HTMLSpanElement>(null)
  const liveHeightRef = useRef<HTMLSpanElement>(null)

  const handlePointerLockChange = useCallback(
    (isPointerLocked: boolean) => console.log(isPointerLocked),
    [],
  )

  useUIFrame(() => {
    liveMouseXRef.current!.textContent = String(mp().mouseX)
    liveMouseYRef.current!.textContent = String(mp().mouseY)
    liveMouseMovementXRef.current!.textContent = String(mp().mouseMovementX)
    liveMouseMovementYRef.current!.textContent = String(mp().mouseMovementY)
    liveWidthRef.current!.textContent = String(mp().width)
    liveHeightRef.current!.textContent = String(mp().height)
  })

  return (
    <>
      <div className="space-x-2 absolute z-10">
        <h1 className="text-center">Mana Potion</h1>
        <div>
          <h2>Fullscreen: {isFullscreen ? 'Yes' : 'No'}</h2>
          <button
            className="bg-slate-100 rounded-md px-2 py-1"
            onClick={isFullscreen ? exitFullscreen : enterFullscreen}
          >
            Toggle Fullscreen
          </button>
        </div>
        <div>
          <h2>Orientation (use after fullscreen on mobile)</h2>
          <button
            className="bg-slate-100 rounded-md px-2 py-1"
            onClick={() => lockOrientation('landscape')}
          >
            Landscape
          </button>
          <button
            className="bg-slate-100 rounded-md px-2 py-1"
            onClick={() => lockOrientation('portrait')}
          >
            Portrait
          </button>
          <button className="bg-slate-100 rounded-md px-2 py-1" onClick={unlockOrientation}>
            Unlock orientation
          </button>
        </div>
        <div>
          <h2>Keyboard lock (use after fullscreen on desktop)</h2>
          <button
            className="bg-slate-100 rounded-md px-2 py-1"
            onClick={() => lockKeys(['Escape'])}
          >
            Lock Esc
          </button>
          <button className="bg-slate-100 rounded-md px-2 py-1" onClick={() => unlockKeys()}>
            Release Esc
          </button>
        </div>
        <div>
          <h2>Pointer is locked: {isPointerLocked ? 'Yes' : 'No'}</h2>
          <button className="bg-slate-100 rounded-md px-2 py-1" onClick={lockPointer}>
            Lock pointer
          </button>
        </div>
        <div>Page is visible: {isPageVisible ? 'Yes' : 'No'}</div>
        <div>Can hover (is desktop): {canHover ? 'Yes' : 'No'}</div>
        <div>
          <b>Mouse buttons</b>
        </div>
        <div>Left: {isLeftMouseDown ? 'Yes' : 'No'} </div>
        <div>Middle: {isMiddleMouseDown ? 'Yes' : 'No'} </div>
        <div>Right: {isRightMouseDown ? 'Yes' : 'No'} </div>
        <div>
          <b>Window size</b>
        </div>
        <div>
          Non-reactive: <span ref={liveWidthRef} />x<span ref={liveHeightRef} />
        </div>
        <div>
          Reactive throttled: {width}x{height}
        </div>
        <div>
          <b>Mouse position</b>
        </div>
        <div>
          Non-reactive: <span ref={liveMouseXRef} /> <span ref={liveMouseYRef} />
        </div>
        <div>
          Reactive throttled: {mouseX} {mouseY}
        </div>
        <div>
          <b>Mouse movement</b>
        </div>
        <div>
          Non-reactive: <span ref={liveMouseMovementXRef} /> <span ref={liveMouseMovementYRef} />
        </div>
        <div>
          Reactive throttled: {mouseMovementX} {mouseMovementY}
        </div>
        <div>
          <div>
            <b>Keyboard</b>
          </div>
          <textarea readOnly className="w-[500px] h-[100px]" value={JSON.stringify(keys)} />
        </div>
      </div>
      <div className="absolute bottom-5 left-1/2 z-10 -translate-x-1/2 transform">
        {renderer}
        <button className="bg-slate-100 rounded-md px-2 py-1 ml-2" onClick={toggleRenderer}>
          Change
        </button>
      </div>
      <Canvas
        forceWebGL={renderer === 'WebGL' || Boolean(import.meta.env.VITE_FORCE_WEBGL)}
        onContextMenu={e => e.preventDefault()}
      >
        <ambientLight intensity={Math.PI / 2} />
        <spotLight
          position={[10, 10, 10]}
          angle={0.15}
          penumbra={1}
          decay={0}
          intensity={Math.PI}
        />
        <pointLight position={[-10, -10, -10]} decay={0} intensity={Math.PI} />
        <Box position={[-1.2, 0, 0]} />
        <Box position={[1.2, 0, 0]} />
      </Canvas>
      <Listeners
        onPointerLockChange={handlePointerLockChange}
        reactiveMouseMoveThrottleDelay={200}
        mouseMovementResetDelay={100}
        reactiveResizeThrottleDelay={200}
        onKeydown={keyState => console.log(keyState)}
      />
    </>
  )
}

export default App
