// examples/svelte/src/components/Item.svelte
<script lang="ts">
  export let isReactive: boolean | undefined = true
  export let name: string | undefined
</script>

<div class="item">
  <span>{isReactive ? '⚡️' : '🗿'}</span>
  <span class="item--main">
    <span class="item--name">{name}</span>
    <span>
      <slot name="label" />
      <slot name="value" />
    </span>
  </span>
  <slot name="extra" />
</div>

// examples/react/src/components/Item.tsx
import type { ReactNode } from 'react'

const Item = ({
  isReactive = true,
  name,
  label,
  value,
  extra,
}: {
  isReactive?: boolean
  name: string
  value?: ReactNode
  label?: ReactNode
  extra?: ReactNode
}) => (
  <div className="item">
    <span>{isReactive ? '⚡️' : '🗿'}</span>
    <span className="item--main">
      <span className="item--name">{name}</span>
      <span>
        {label}
        {value}
      </span>
    </span>
    {extra}
  </div>
)

export default Item
